#!/usr/bin/env python3
"""hook_scaffold.py: scaffold a Claude Code hook in the cc-hooks pattern from a short spec, with fixtures and a test.

Input: a spec file, JSON or `key: value` lines:

    name: deny-env-read
    event: PreToolUse              # PreToolUse, PostToolUse, UserPromptSubmit, Stop or SessionStart
    matcher: Bash                  # tool events only; omit to match every tool
    action: block                  # block, warn, allow or modify
    pattern: (^|\\s)cat\\s+\\S*\\.env\\b
    message: Reading .env prints secrets into the transcript.
    match_example: cat .env
    nomatch_example: ls -la
    field: command                 # optional: command, file_path, tool_input, prompt, last_assistant_message, source
    replacement: ...               # modify only: what the matched text becomes (re.sub syntax)
    fail: closed                   # optional: closed or open when the payload cannot be read

Decision table (what each action prints, through the cc-hooks builders):

    action   PreToolUse            PostToolUse            UserPromptSubmit   Stop               SessionStart
    block    deny(message)         block(message)         block(message)     block(message)     refused
    warn     add_context(message)  add_context(message)   add_context        add_context        add_context
    allow    allow(message)        refused                refused            refused            refused
    modify   update_input(ask)     refused                refused            refused            refused

Files (written under --out DIR, or printed when --out is not given):
  <name>.py                  the hook: reads the event with cc_hooks.read_event, tests the field against the pattern,
                             prints the decision, and gives no decision otherwise
  test_<name>.py             a pytest file that feeds each fixture to the hook in-process and checks the decision
  fixtures/<name>/*.json     match.json and nomatch.json in the cc-hooks fixture format, for `cc-hooks test`
  <name>.settings.json       the hooks block to merge into .claude/settings.json (exec form: python3 plus the path)

Checks before writing: the pattern compiles, match_example matches and nomatch_example does not, the action is allowed
for the event, the message does not reference environment variables (a hook message must never print secrets), and
existing files are not overwritten without --force.

Exit codes: 0 scaffolded, 1 scaffolded with warnings a person should read (allow skips the permission prompt, block
on PostToolUse cannot undo the tool call, fail open on a block hook, no matcher on a tool event), 2 bad spec or a
file already exists.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

EVENTS = ("PreToolUse", "PostToolUse", "UserPromptSubmit", "Stop", "SessionStart")
ACTIONS = ("block", "warn", "allow", "modify")
ALLOWED = {
    "block": {"PreToolUse", "PostToolUse", "UserPromptSubmit", "Stop"},
    "warn": set(EVENTS),
    "allow": {"PreToolUse"},
    "modify": {"PreToolUse"},
}
DEFAULT_FIELD = {"UserPromptSubmit": "prompt", "Stop": "last_assistant_message", "SessionStart": "source"}
FIELDS = {"command", "file_path", "tool_input", "prompt", "last_assistant_message", "source"}
TOOL_FIELDS = {"command", "file_path", "tool_input"}
REQUIRED = ("name", "event", "action", "pattern", "message", "match_example", "nomatch_example")
ENV_RE = re.compile(r"\$\{?[A-Za-z_][A-Za-z0-9_]*|os\.environ|getenv")

HOOK = '''#!/usr/bin/env python3
"""{name}: {event} hook generated by hook_scaffold.py.

Matcher: {matcher_text}. Action: {action}. It tests {field} against PATTERN and, on a match, {effect}.
Anything else gets no decision, so the normal flow applies. If the payload cannot be read it fails {fail}.

Test it with:  cc-hooks test {fixtures} --settings {settings} --cwd .
"""

from __future__ import annotations

import json
import re

from cc_hooks import HookInputError, {imports}, no_decision, read_event

PATTERN = re.compile({pattern!r})
MESSAGE = {message!r}
REPLACEMENT = {replacement!r}


def subject(event) -> str:
    """The text the pattern is tested against: {field}."""
    {subject}


def main() -> None:
    try:
        event = read_event(strict=False)
    except HookInputError:
        {on_bad_input}
    if not isinstance(event, {event}):
        no_decision().exit()
{guard}    text = subject(event)
    if PATTERN.search(text):
        {decision}
    no_decision().exit()


if __name__ == "__main__":
    main()
'''

TEST = '''"""Tests for {name}.py, generated by hook_scaffold.py.

Each fixture in fixtures/{name}/ is fed to the hook on standard input, in this process, and the decision it prints
must equal expect.decision. Needs the cc-hooks library importable by this Python. `cc-hooks test` runs the same
fixtures through your settings, matchers included.
"""

from __future__ import annotations

import io
import json
import runpy
import sys
from contextlib import redirect_stdout
from pathlib import Path

import pytest

pytest.importorskip("cc_hooks")

HERE = Path(__file__).resolve().parent
HOOK = HERE / "{name}.py"
FIXTURES = sorted((HERE / "fixtures" / "{name}").glob("*.json"))


def decision_of(stdout: str, code: int) -> str:
    if code == 2:
        return "block"
    if not stdout.strip():
        return "none"
    data = json.loads(stdout)
    specific = data.get("hookSpecificOutput", {{}})
    if specific.get("permissionDecision"):
        return specific["permissionDecision"]
    if data.get("decision") == "block":
        return "block"
    if specific.get("additionalContext"):
        return "context"
    return "none"


@pytest.mark.parametrize("fixture", FIXTURES, ids=[f.stem for f in FIXTURES])
def test_fixture(fixture, monkeypatch):
    case = json.loads(fixture.read_text(encoding="utf-8"))
    monkeypatch.setattr(sys, "stdin", io.StringIO(json.dumps(case["event"])))
    out = io.StringIO()
    code = 0
    with redirect_stdout(out):
        try:
            runpy.run_path(str(HOOK), run_name="__main__")
        except SystemExit as exc:
            code = int(exc.code or 0)
    assert decision_of(out.getvalue(), code) == case["expect"]["decision"]


def test_there_are_fixtures():
    assert len(FIXTURES) >= 2
'''


class SpecError(Exception):
    """Bad spec: the message is printed and the script exits 2."""


def read_spec(path: Path) -> dict[str, str]:
    if not path.is_file():
        raise SpecError(f"{path}: spec not found")
    text = path.read_text(encoding="utf-8")
    if text.lstrip().startswith("{"):
        try:
            data = json.loads(text)
        except json.JSONDecodeError as exc:
            raise SpecError(f"{path}: invalid JSON: {exc}") from exc
        if not isinstance(data, dict):
            raise SpecError(f"{path}: expected a JSON object")
        return {str(k): str(v) for k, v in data.items()}
    spec: dict[str, str] = {}
    for number, line in enumerate(text.splitlines(), start=1):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = re.match(r"^([a-z_]+):\s?(.*)$", line)
        if not m:
            raise SpecError(f"{path}:{number}: expected 'key: value'")
        value = re.sub(r"\s+#\s.*$", "", m.group(2)).strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        spec[m.group(1)] = value
    return spec


def validate(spec: dict[str, str]) -> tuple[dict[str, str], list[str]]:
    missing = [k for k in REQUIRED if k not in spec or (not spec[k] and not k.endswith("_example"))]
    if missing:
        raise SpecError(f"spec is missing: {', '.join(missing)}")
    s = dict(spec)
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", s["name"]):
        raise SpecError("name must be lowercase letters, digits, '-' or '_'")
    if s["event"] not in EVENTS:
        raise SpecError(f"event must be one of {', '.join(EVENTS)}")
    if s["action"] not in ACTIONS:
        raise SpecError(f"action must be one of {', '.join(ACTIONS)}")
    if s["event"] not in ALLOWED[s["action"]]:
        raise SpecError(f"action {s['action']!r} is not available on {s['event']} (see the decision table)")
    tool_event = s["event"] in ("PreToolUse", "PostToolUse")
    s.setdefault("matcher", "")
    if not tool_event and s["matcher"]:
        raise SpecError(f"{s['event']} hooks take no tool matcher here")
    default = DEFAULT_FIELD.get(s["event"]) or ("command" if re.search(r"\bBash\b", s["matcher"]) else "file_path")
    s["field"] = s.get("field") or default
    if s["field"] not in FIELDS or (s["field"] in TOOL_FIELDS) != tool_event:
        raise SpecError(f"field {s['field']!r} does not fit {s['event']}")
    if s["action"] == "modify":
        if s["field"] not in ("command", "file_path") or "replacement" not in s:
            raise SpecError("modify needs field command or file_path and a replacement")
    try:
        pattern = re.compile(s["pattern"])
    except re.error as exc:
        raise SpecError(f"pattern does not compile: {exc}") from exc
    if not pattern.search(s["match_example"]):
        raise SpecError("match_example does not match the pattern")
    if pattern.search(s["nomatch_example"]):
        raise SpecError("nomatch_example matches the pattern")
    if ENV_RE.search(s["message"]):
        raise SpecError("message references an environment variable; a hook message must never print secrets")
    s.setdefault("fail", "closed" if s["action"] == "block" and s["event"] == "PreToolUse" else "open")
    if s["fail"] not in ("open", "closed"):
        raise SpecError("fail must be open or closed")
    tool = s.get("tool_name") or (s["matcher"].split("|")[0] if re.fullmatch(r"[\w|]+", s["matcher"]) else "")
    if tool_event and not tool:
        raise SpecError("give tool_name for the fixtures when the matcher is empty or a regular expression")
    s["tool_name"] = tool
    warnings = []
    if s["action"] == "allow":
        warnings.append("allow skips the permission prompt for every matching call; prefer warn or no decision")
    if s["action"] == "block" and s["event"] == "PostToolUse":
        warnings.append("block on PostToolUse tells Claude after the tool already ran; it cannot undo the call")
    if s["action"] == "block" and s["fail"] == "open":
        warnings.append("a block hook that fails open lets the call through when the payload cannot be read")
    if tool_event and not s["matcher"]:
        warnings.append("no matcher: the hook runs on every tool call")
    return s, warnings


def payload(s: dict[str, str], example: str) -> dict:
    event: dict = {"session_id": "fixture", "cwd": "/tmp/hook-fixture", "hook_event_name": s["event"]}
    if s["event"] in ("PreToolUse", "PostToolUse"):
        key = s["field"] if s["field"] != "tool_input" else "value"
        event.update({"tool_name": s["tool_name"], "tool_input": {key: example}})
        if s["event"] == "PostToolUse":
            event["tool_response"] = {}
    elif s["event"] == "Stop":
        event.update({"stop_hook_active": False, "last_assistant_message": example})
    else:
        event[s["field"]] = example
    return event


def expected(s: dict[str, str]) -> str:
    if s["action"] == "warn":
        return "context"
    if s["action"] == "block":
        return "deny" if s["event"] == "PreToolUse" else "block"
    return "ask" if s["action"] == "modify" else "allow"


def build(s: dict[str, str], hook_dir: str) -> dict[str, str]:
    name, event = s["name"], s["event"]
    decision = {
        "block": "deny(MESSAGE).exit()" if event == "PreToolUse" else f'block(MESSAGE, event="{event}").exit()',
        "warn": f'add_context(MESSAGE, event="{event}").exit()',
        "allow": "allow(MESSAGE).exit()",
        "modify": "update_input({**event.tool_input, "
        + repr(s["field"])
        + ': PATTERN.sub(REPLACEMENT, text)}, decision="ask", reason=MESSAGE).exit()',
    }[s["action"]]
    builder = {"block": "deny" if event == "PreToolUse" else "block", "warn": "add_context"}.get(s["action"])
    builder = builder or {"allow": "allow", "modify": "update_input"}[s["action"]]
    imports = sorted({builder, event} | ({"deny"} if s["fail"] == "closed" and event == "PreToolUse" else set()))
    if s["fail"] == "closed" and event == "PreToolUse":
        on_bad = 'deny("The hook could not read its input, so it failed closed.").exit()'
    else:
        on_bad = "no_decision().exit()"
    if s["field"] == "tool_input":
        subject = "return json.dumps(event.tool_input or {}, sort_keys=True)"
    else:
        subject = f'return str(getattr(event, "{s["field"]}", "") or "")'
    guard = "    if event.stop_hook_active:\n        no_decision().exit()\n" if event == "Stop" else ""
    effects = {
        "block": "blocks with MESSAGE",
        "warn": "adds MESSAGE to Claude's context",
        "allow": "allows the call without a prompt",
        "modify": "rewrites the matched text with REPLACEMENT and asks the user to confirm",
    }
    fixtures = f"{hook_dir}/fixtures/{name}"
    settings = f"{hook_dir}/{name}.settings.json"
    hook = HOOK.format(
        name=name,
        event=event,
        matcher_text=s["matcher"] or "(none)",
        action=s["action"],
        field=s["field"],
        effect=effects[s["action"]],
        fail=s["fail"],
        fixtures=fixtures,
        settings=settings,
        imports=", ".join(imports),
        pattern=s["pattern"],
        message=s["message"],
        replacement=s.get("replacement", ""),
        on_bad_input=on_bad,
        guard=guard,
        decision=decision,
        subject=subject,
    )
    group: dict = {"matcher": s["matcher"]} if s["matcher"] else {}
    group["hooks"] = [
        {
            "type": "command",
            "command": "python3",
            "args": [f"${{CLAUDE_PROJECT_DIR}}/{hook_dir}/{name}.py"],
            "timeout": 10,
        }
    ]
    match = {"event": payload(s, s["match_example"]), "expect": {"decision": expected(s)}}
    nomatch = {"event": payload(s, s["nomatch_example"]), "expect": {"decision": "none"}}
    return {
        f"{name}.py": hook,
        f"test_{name}.py": TEST.format(name=name),
        f"fixtures/{name}/match.json": json.dumps(match, indent=2) + "\n",
        f"fixtures/{name}/nomatch.json": json.dumps(nomatch, indent=2) + "\n",
        f"{name}.settings.json": json.dumps({"hooks": {event: [group]}}, indent=2) + "\n",
    }


def render(files: dict[str, str], warnings: list[str]) -> str:
    out = ["# Hook scaffold", ""]
    for w in warnings:
        out.append(f"Warning: {w}")
    if warnings:
        out.append("")
    for path, text in files.items():
        lang = "python" if path.endswith(".py") else "json"
        out += [f"## {path}", "", f"```{lang}", text.rstrip("\n"), "```", ""]
    return "\n".join(out)


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="hook_scaffold.py",
        description="Scaffold a Claude Code hook (cc-hooks pattern) with fixtures, a pytest file and the settings "
        "block, from a short spec.",
        epilog="Exit codes: 0 scaffolded, 1 scaffolded with warnings, 2 bad spec or a file already exists.",
    )
    p.add_argument("spec", help="spec file, JSON or 'key: value' lines")
    p.add_argument("--hook-dir", default=".claude/hooks", help="project-relative folder the hook will live in")
    p.add_argument("--force", action="store_true", help="overwrite files that already exist under --out")
    p.add_argument("--json", action="store_true", help="print the files and warnings as JSON instead of Markdown")
    p.add_argument("--out", default=None, help="write the files into this folder instead of printing them")
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        spec, warnings = validate(read_spec(Path(args.spec)))
        files = build(spec, args.hook_dir.strip("/") or ".")
        if args.out:
            root = Path(args.out)
            clashes = [p for p in files if (root / p).exists()]
            if clashes and not args.force:
                raise SpecError(f"would overwrite {', '.join(clashes)} under {root}; pass --force")
    except SpecError as exc:
        print(f"hook_scaffold.py: {exc}", file=sys.stderr)
        return 2
    if args.out:
        for path, text in files.items():
            target = Path(args.out) / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text, encoding="utf-8", newline="\n")
        summary = {"written": sorted(files), "out": args.out, "warnings": warnings}
        sys.stdout.write(
            json.dumps(summary, indent=2) + "\n"
            if args.json
            else "".join(f"wrote {args.out}/{p}\n" for p in files) + "".join(f"warning: {w}\n" for w in warnings)
        )
    else:
        sys.stdout.write(
            json.dumps({"files": files, "warnings": warnings}, indent=2, sort_keys=True) + "\n"
            if args.json
            else render(files, warnings)
        )
    return 1 if warnings else 0


if __name__ == "__main__":
    sys.exit(main())
